# Generated by Django 6.0.3 on 2026-03-31 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportsapp', '0002_alter_faultreport_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faultreport',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='faultreport',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
